spring:
  application:
    name: clean-arch
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:CleanArch
  data:
    jpa:
      repositories:
        bootstrap-mode: default

user-config:
  name: ''
  phone: ''
